# comment

package:
  name: antarna
  version: "2.0.1"



source:
  git_url: https://github.com/RobertKleinkauf/antarna.git



build:
  number: 1
  string: agnostic_ant
  skip: True # [osx]



requirements:
  build:
    - python
    - argparse
    - numpy
    - uuid
    - networkx
    - scipy



  run:
    - python
    - argparse
    - numpy
    - uuid
    - networkx
    - scipy

test:
  commands:
    - echo "Hello"

about:
  license: The MIT License (MIT)
  summary: antaRNA is a python based implementation of ant-colony optimization of the RNA inverse folding problem.
