package:
  name: antarna
  version: "2.0.1.1"

source:
  url:: https://github.com/RobertKleinkauf/antarna/archive/v2.0.1.1.tar.gz
  

build:
  number: 0
  string: agnostic_ant

requirements:
  build:
    - python
    - numpy
    - uuid
    - networkx
    - scipy
  run:
    - python
    - numpy
    - uuid
    - networkx
    - scipy
    - viennarna

test:
  commands:
    - antarna.py -tGC 0.5 MFE -Cstr "(((((...)))))"
    - antarna.py -tGC 0.5 DP --accuracy "((((((....)))))).((((((....)))))) UB 0.5" --accuracy "((((((((((((((.....)))))))))))))) UB 0.5"
    - antarna.py -tGC 0.5 DP -Cstr "(((((...)))))................" --diff-accuracy "................(((((...))))) UB 0.0 B 1.0" --diff-accuracy "........(((((...)))))........ UB 1.0 B 0.0"

about:
  home: https://github.com/RobertKleinkauf/antarna
  license: The MIT License (MIT)
  license_file: LICENSE
  summary: antaRNA is a python based implementation of ant-colony optimization of the RNA inverse folding problem.
